# Generated by Django 3.0.5 on 2026-06-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedyrequest',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='remedyrequest',
            name='suggestion',
        ),
        migrations.AddField(
            model_name='remedyrequest',
            name='predicted_disease',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='remedyrequest',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remedyrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
