# Generated by Django 6.0.6 on 2026-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedy', '0002_auto_20260615_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedyrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
