# Generated by Django 6.0.6 on 2026-07-15 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedy', '0003_alter_remedyrequest_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remedyrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='remedyrequest',
            old_name='recommendation',
            new_name='advice',
        ),
        migrations.AddField(
            model_name='remedyrequest',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='remedyrequest',
            name='remedies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='remedyrequest',
            name='severity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='remedyrequest',
            name='predicted_disease',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='remedyrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remedy_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
