# Generated by Django 6.0.6 on 2026-07-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='intent',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='safety_level',
            field=models.CharField(default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='topic',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
